apiVersion: apps/v1
kind: Deployment
metadata:
  name: astro-sample
  labels:
    app: astro-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: astro-sample
  template:
    metadata:
      labels:
        app: astro-sample
    spec:
      containers:
      - name: astro-sample
        image: astro-sample:latest
        ports:
        - containerPort: 8080
          name: http
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
      securityContext:
        runAsNonRoot: true
---
apiVersion: v1
kind: Service
metadata:
  name: astro-sample
  labels:
    app: astro-sample
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: astro-sample
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: astro-sample
  labels:
    app: astro-sample
spec:
  to:
    kind: Service
    name: astro-sample
  port:
    targetPort: http